// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.predictdb.entities.task;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DocumentNominalLabelId generated by hbm2java
 */
@Embeddable
public class DocumentNominalLabelId implements java.io.Serializable {

	private long documentId;
	private int nominalLabelId;
	private int userId;

	public DocumentNominalLabelId() {
	}

	public DocumentNominalLabelId(long documentId, int nominalLabelId,
			int userId) {
		this.documentId = documentId;
		this.nominalLabelId = nominalLabelId;
		this.userId = userId;
	}

	@Column(name = "documentID", nullable = false)
	public long getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(long documentId) {
		this.documentId = documentId;
	}

	@Column(name = "nominalLabelID", nullable = false)
	public int getNominalLabelId() {
		return this.nominalLabelId;
	}

	public void setNominalLabelId(int nominalLabelId) {
		this.nominalLabelId = nominalLabelId;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocumentNominalLabelId))
			return false;
		DocumentNominalLabelId castOther = (DocumentNominalLabelId) other;

		return (this.getDocumentId() == castOther.getDocumentId())
				&& (this.getNominalLabelId() == castOther.getNominalLabelId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getDocumentId();
		result = 37 * result + this.getNominalLabelId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
