// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.predictdb.entities.task;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TaskAssignmentId generated by hbm2java
 */
@Embeddable
public class TaskAssignmentId implements java.io.Serializable {

	private long documentId;
	private int userId;

	public TaskAssignmentId() {
	}

	public TaskAssignmentId(long documentId, int userId) {
		this.documentId = documentId;
		this.userId = userId;
	}

	@Column(name = "documentID", nullable = false)
	public long getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(long documentId) {
		this.documentId = documentId;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaskAssignmentId))
			return false;
		TaskAssignmentId castOther = (TaskAssignmentId) other;

		return (this.getDocumentId() == castOther.getDocumentId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getDocumentId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
