// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.predictdb.entities.task;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TaskAnswerId generated by hbm2java
 */
@Embeddable
public class TaskAnswerId implements java.io.Serializable {

	private long taskId;
	private long documentId;
	private int userId;

	public TaskAnswerId() {
	}

	public TaskAnswerId(long taskId, long documentId, int userId) {
		this.taskId = taskId;
		this.documentId = documentId;
		this.userId = userId;
	}

	@Column(name = "taskID", unique = true, nullable = false)
	public long getTaskId() {
		return this.taskId;
	}

	public void setTaskId(long taskId) {
		this.taskId = taskId;
	}

	@Column(name = "documentID", nullable = false)
	public long getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(long documentId) {
		this.documentId = documentId;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaskAnswerId))
			return false;
		TaskAnswerId castOther = (TaskAnswerId) other;

		return (this.getTaskId() == castOther.getTaskId())
				&& (this.getDocumentId() == castOther.getDocumentId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getTaskId();
		result = 37 * result + (int) this.getDocumentId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
