// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0

/**
 * Implements the entity corresponding to the crisis_type table in the aidr_predict DB
 * 
 * @author Koushik
 */
package qa.qcri.aidr.manager.persistence.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/*
 * CrisisType generated by hbm2java
 */
@Entity
@Table(name = "crisis_type")
public class CrisisType extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8074463052776843105L;
	
	@Column(name = "name", nullable = false, length = 140)
	private String name;
	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
