// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.predictdb.entities.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActiveAttributesId generated by hbm2java
 */
@Embeddable
public class ActiveAttributesId implements java.io.Serializable {

	private int crisisId;
	private String attributeInfo;

	public ActiveAttributesId() {
	}

	public ActiveAttributesId(int crisisId) {
		this.crisisId = crisisId;
	}

	public ActiveAttributesId(int crisisId, String attributeInfo) {
		this.crisisId = crisisId;
		this.attributeInfo = attributeInfo;
	}

	@Column(name = "crisisID", nullable = false)
	public int getCrisisId() {
		return this.crisisId;
	}

	public void setCrisisId(int crisisId) {
		this.crisisId = crisisId;
	}

	@Column(name = "attributeInfo", length = 358)
	public String getAttributeInfo() {
		return this.attributeInfo;
	}

	public void setAttributeInfo(String attributeInfo) {
		this.attributeInfo = attributeInfo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActiveAttributesId))
			return false;
		ActiveAttributesId castOther = (ActiveAttributesId) other;

		return (this.getCrisisId() == castOther.getCrisisId())
				&& ((this.getAttributeInfo() == castOther.getAttributeInfo()) || (this
						.getAttributeInfo() != null
						&& castOther.getAttributeInfo() != null && this
						.getAttributeInfo()
						.equals(castOther.getAttributeInfo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCrisisId();
		result = 37
				* result
				+ (getAttributeInfo() == null ? 0 : this.getAttributeInfo()
						.hashCode());
		return result;
	}

}
