// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.predictdb.entities.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ActiveAttributesInner generated by hbm2java
 */
@Entity
@Table(name = "active_attributes_inner", catalog = "aidr_predict")
public class ActiveAttributesInner implements java.io.Serializable {

	private ActiveAttributesInnerId id;

	public ActiveAttributesInner() {
	}

	public ActiveAttributesInner(ActiveAttributesInnerId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "crisisId", column = @Column(name = "crisisID", nullable = false)),
			@AttributeOverride(name = "nominalAttributeId", column = @Column(name = "nominalAttributeID", nullable = false)),
			@AttributeOverride(name = "name", column = @Column(name = "name", nullable = false, length = 140)),
			@AttributeOverride(name = "description", column = @Column(name = "description", nullable = false, length = 600)),
			@AttributeOverride(name = "labels", column = @Column(name = "labels", length = 352)) })
	public ActiveAttributesInnerId getId() {
		return this.id;
	}

	public void setId(ActiveAttributesInnerId id) {
		this.id = id;
	}

}
