// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.predictdb.entities.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ActiveAttributes generated by hbm2java
 */
@Entity
@Table(name = "active_attributes", catalog = "aidr_predict")
public class ActiveAttributes implements java.io.Serializable {

	private ActiveAttributesId id;

	public ActiveAttributes() {
	}

	public ActiveAttributes(ActiveAttributesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "crisisId", column = @Column(name = "crisisID", nullable = false)),
			@AttributeOverride(name = "attributeInfo", column = @Column(name = "attributeInfo", length = 358)) })
	public ActiveAttributesId getId() {
		return this.id;
	}

	public void setId(ActiveAttributesId id) {
		this.id = id;
	}

}
