// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.predictdb.entities.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActiveAttributesInnerId generated by hbm2java
 */
@Embeddable
public class ActiveAttributesInnerId implements java.io.Serializable {

	private int crisisId;
	private int nominalAttributeId;
	private String name;
	private String description;
	private String labels;

	public ActiveAttributesInnerId() {
	}

	public ActiveAttributesInnerId(int crisisId, int nominalAttributeId,
			String name, String description) {
		this.crisisId = crisisId;
		this.nominalAttributeId = nominalAttributeId;
		this.name = name;
		this.description = description;
	}

	public ActiveAttributesInnerId(int crisisId, int nominalAttributeId,
			String name, String description, String labels) {
		this.crisisId = crisisId;
		this.nominalAttributeId = nominalAttributeId;
		this.name = name;
		this.description = description;
		this.labels = labels;
	}

	@Column(name = "crisisID", nullable = false)
	public int getCrisisId() {
		return this.crisisId;
	}

	public void setCrisisId(int crisisId) {
		this.crisisId = crisisId;
	}

	@Column(name = "nominalAttributeID", nullable = false)
	public int getNominalAttributeId() {
		return this.nominalAttributeId;
	}

	public void setNominalAttributeId(int nominalAttributeId) {
		this.nominalAttributeId = nominalAttributeId;
	}

	@Column(name = "name", nullable = false, length = 140)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 600)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "labels", length = 352)
	public String getLabels() {
		return this.labels;
	}

	public void setLabels(String labels) {
		this.labels = labels;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActiveAttributesInnerId))
			return false;
		ActiveAttributesInnerId castOther = (ActiveAttributesInnerId) other;

		return (this.getCrisisId() == castOther.getCrisisId())
				&& (this.getNominalAttributeId() == castOther
						.getNominalAttributeId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getLabels() == castOther.getLabels()) || (this
						.getLabels() != null && castOther.getLabels() != null && this
						.getLabels().equals(castOther.getLabels())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCrisisId();
		result = 37 * result + this.getNominalAttributeId();
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37 * result
				+ (getLabels() == null ? 0 : this.getLabels().hashCode());
		return result;
	}

}
