// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.predictdb.entities.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NominalAttributeDependentLabelId generated by hbm2java
 */
@Embeddable
public class NominalAttributeDependentLabelId implements java.io.Serializable {

	private Long nominalAttributeId;
	private Long nominalLabelId;

	public NominalAttributeDependentLabelId() {
	}

	public NominalAttributeDependentLabelId(Long nominalAttributeId,
			Long nominalLabelId) {
		this.nominalAttributeId = nominalAttributeId;
		this.nominalLabelId = nominalLabelId;
	}

	@Column(name = "nominalAttributeID", nullable = false)
	public Long getNominalAttributeId() {
		return this.nominalAttributeId;
	}

	public void setNominalAttributeId(Long nominalAttributeId) {
		this.nominalAttributeId = nominalAttributeId;
	}

	@Column(name = "nominalLabelID", nullable = false)
	public Long getNominalLabelId() {
		return this.nominalLabelId;
	}

	public void setNominalLabelId(Long nominalLabelId) {
		this.nominalLabelId = nominalLabelId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NominalAttributeDependentLabelId))
			return false;
		NominalAttributeDependentLabelId castOther = (NominalAttributeDependentLabelId) other;

		return (this.getNominalAttributeId() == castOther
				.getNominalAttributeId())
				&& (this.getNominalLabelId() == castOther.getNominalLabelId());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNominalAttributeId().intValue();
		result = 37 * result + this.getNominalLabelId().intValue();
		return result;
	}

}
