// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.predictdb.entities.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NominalLabelEvaluationDataId generated by hbm2java
 */
@Embeddable
public class NominalLabelEvaluationDataId implements java.io.Serializable {

	private long documentId;
	private int crisisId;
	private int nominalLabelId;
	private int nominalAttributeId;
	private String wordFeatures;

	public NominalLabelEvaluationDataId() {
	}

	public NominalLabelEvaluationDataId(long documentId, int crisisId,
			int nominalLabelId, int nominalAttributeId) {
		this.documentId = documentId;
		this.crisisId = crisisId;
		this.nominalLabelId = nominalLabelId;
		this.nominalAttributeId = nominalAttributeId;
	}

	public NominalLabelEvaluationDataId(long documentId, int crisisId,
			int nominalLabelId, int nominalAttributeId, String wordFeatures) {
		this.documentId = documentId;
		this.crisisId = crisisId;
		this.nominalLabelId = nominalLabelId;
		this.nominalAttributeId = nominalAttributeId;
		this.wordFeatures = wordFeatures;
	}

	@Column(name = "documentID", nullable = false)
	public long getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(long documentId) {
		this.documentId = documentId;
	}

	@Column(name = "crisisID", nullable = false)
	public int getCrisisId() {
		return this.crisisId;
	}

	public void setCrisisId(int crisisId) {
		this.crisisId = crisisId;
	}

	@Column(name = "nominalLabelID", nullable = false)
	public int getNominalLabelId() {
		return this.nominalLabelId;
	}

	public void setNominalLabelId(int nominalLabelId) {
		this.nominalLabelId = nominalLabelId;
	}

	@Column(name = "nominalAttributeID", nullable = false)
	public int getNominalAttributeId() {
		return this.nominalAttributeId;
	}

	public void setNominalAttributeId(int nominalAttributeId) {
		this.nominalAttributeId = nominalAttributeId;
	}

	@Column(name = "wordFeatures", length = 65535)
	public String getWordFeatures() {
		return this.wordFeatures;
	}

	public void setWordFeatures(String wordFeatures) {
		this.wordFeatures = wordFeatures;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NominalLabelEvaluationDataId))
			return false;
		NominalLabelEvaluationDataId castOther = (NominalLabelEvaluationDataId) other;

		return (this.getDocumentId() == castOther.getDocumentId())
				&& (this.getCrisisId() == castOther.getCrisisId())
				&& (this.getNominalLabelId() == castOther.getNominalLabelId())
				&& (this.getNominalAttributeId() == castOther
						.getNominalAttributeId())
				&& ((this.getWordFeatures() == castOther.getWordFeatures()) || (this
						.getWordFeatures() != null
						&& castOther.getWordFeatures() != null && this
						.getWordFeatures().equals(castOther.getWordFeatures())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getDocumentId();
		result = 37 * result + this.getCrisisId();
		result = 37 * result + this.getNominalLabelId();
		result = 37 * result + this.getNominalAttributeId();
		result = 37
				* result
				+ (getWordFeatures() == null ? 0 : this.getWordFeatures()
						.hashCode());
		return result;
	}

}
