// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.predictdb.entities.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NominalLabel generated by hbm2java
 */
@Entity
@Table(name = "nominal_label", catalog = "aidr_predict")
public class NominalLabel implements java.io.Serializable {

	private Integer nominalLabelId;
	private NominalAttribute nominalAttribute;
	private String nominalLabelCode;
	private String name;
	private String description;
	private int sequence;
	private Set modelNominalLabels = new HashSet(0);
	private Set nominalAttributeDependentLabels = new HashSet(0);
	private Set documentNominalLabels = new HashSet(0);

	public NominalLabel() {
	}

	public NominalLabel(NominalAttribute nominalAttribute,
			String nominalLabelCode, String name, String description,
			int sequence) {
		this.nominalAttribute = nominalAttribute;
		this.nominalLabelCode = nominalLabelCode;
		this.name = name;
		this.description = description;
		this.sequence = sequence;
	}

	public NominalLabel(NominalAttribute nominalAttribute,
			String nominalLabelCode, String name, String description,
			int sequence, Set modelNominalLabels,
			Set nominalAttributeDependentLabels, Set documentNominalLabels) {
		this.nominalAttribute = nominalAttribute;
		this.nominalLabelCode = nominalLabelCode;
		this.name = name;
		this.description = description;
		this.sequence = sequence;
		this.modelNominalLabels = modelNominalLabels;
		this.nominalAttributeDependentLabels = nominalAttributeDependentLabels;
		this.documentNominalLabels = documentNominalLabels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "nominalLabelID", unique = true, nullable = false)
	public Integer getNominalLabelId() {
		return this.nominalLabelId;
	}

	public void setNominalLabelId(Integer nominalLabelId) {
		this.nominalLabelId = nominalLabelId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nominalAttributeID", nullable = false)
	public NominalAttribute getNominalAttribute() {
		return this.nominalAttribute;
	}

	public void setNominalAttribute(NominalAttribute nominalAttribute) {
		this.nominalAttribute = nominalAttribute;
	}

	@Column(name = "nominalLabelCode", nullable = false, length = 64)
	public String getNominalLabelCode() {
		return this.nominalLabelCode;
	}

	public void setNominalLabelCode(String nominalLabelCode) {
		this.nominalLabelCode = nominalLabelCode;
	}

	@Column(name = "name", nullable = false, length = 140)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 600)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "sequence", nullable = false)
	public int getSequence() {
		return this.sequence;
	}

	public void setSequence(int sequence) {
		this.sequence = sequence;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nominalLabel")
	public Set getModelNominalLabels() {
		return this.modelNominalLabels;
	}

	public void setModelNominalLabels(Set modelNominalLabels) {
		this.modelNominalLabels = modelNominalLabels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nominalLabel")
	public Set getNominalAttributeDependentLabels() {
		return this.nominalAttributeDependentLabels;
	}

	public void setNominalAttributeDependentLabels(
			Set nominalAttributeDependentLabels) {
		this.nominalAttributeDependentLabels = nominalAttributeDependentLabels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nominalLabel")
	public Set getDocumentNominalLabels() {
		return this.documentNominalLabels;
	}

	public void setDocumentNominalLabels(Set documentNominalLabels) {
		this.documentNominalLabels = documentNominalLabels;
	}

}
