// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.predictdb.entities.misc;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CrisisType generated by hbm2java
 */
@Entity
@Table(name = "crisis_type", catalog = "aidr_predict")
public class CrisisType implements java.io.Serializable {

	private Long crisisTypeId;
	private String name;
	private Set crisises = new HashSet(0);

	public CrisisType() {
	}

	public CrisisType(String name) {
		this.name = name;
	}

	public CrisisType(String name, Set crisises) {
		this.name = name;
		this.crisises = crisises;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "crisisTypeID", unique = true, nullable = false)
	public Integer getCrisisTypeId() {
		return this.crisisTypeId;
	}

	public void setCrisisTypeId(Integer crisisTypeId) {
		this.crisisTypeId = crisisTypeId;
	}

	@Column(name = "name", nullable = false, length = 140)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crisisType")
	public Set getCrisises() {
		return this.crisises;
	}

	public void setCrisises(Set crisises) {
		this.crisises = crisises;
	}

}
