// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.predictdb.entities.misc;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TaskBuffer generated by hbm2java
 */
@Entity
@Table(name = "task_buffer", catalog = "aidr_predict")
public class TaskBuffer implements java.io.Serializable {

	private TaskBufferId id;

	public TaskBuffer() {
	}

	public TaskBuffer(TaskBufferId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "documentId", column = @Column(name = "documentID", nullable = false)),
			@AttributeOverride(name = "crisisId", column = @Column(name = "crisisID", nullable = false)),
			@AttributeOverride(name = "attributeInfo", column = @Column(name = "attributeInfo", length = 358)),
			@AttributeOverride(name = "language", column = @Column(name = "language", nullable = false, length = 5)),
			@AttributeOverride(name = "doctype", column = @Column(name = "doctype", nullable = false, length = 20)),
			@AttributeOverride(name = "data", column = @Column(name = "data", nullable = false, length = 65535)),
			@AttributeOverride(name = "valueAsTrainingSample", column = @Column(name = "valueAsTrainingSample", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "assignedCount", column = @Column(name = "assignedCount", precision = 23, scale = 0)) })
	public TaskBufferId getId() {
		return this.id;
	}

	public void setId(TaskBufferId id) {
		this.id = id;
	}

}
