// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.predictdb.entities.misc;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TaskBufferId generated by hbm2java
 */
@Embeddable
public class TaskBufferId implements java.io.Serializable {

	private long documentId;
	private int crisisId;
	private String attributeInfo;
	private String language;
	private String doctype;
	private String data;
	private double valueAsTrainingSample;
	private BigDecimal assignedCount;

	public TaskBufferId() {
	}

	public TaskBufferId(long documentId, int crisisId, String language,
			String doctype, String data, double valueAsTrainingSample) {
		this.documentId = documentId;
		this.crisisId = crisisId;
		this.language = language;
		this.doctype = doctype;
		this.data = data;
		this.valueAsTrainingSample = valueAsTrainingSample;
	}

	public TaskBufferId(long documentId, int crisisId, String attributeInfo,
			String language, String doctype, String data,
			double valueAsTrainingSample, BigDecimal assignedCount) {
		this.documentId = documentId;
		this.crisisId = crisisId;
		this.attributeInfo = attributeInfo;
		this.language = language;
		this.doctype = doctype;
		this.data = data;
		this.valueAsTrainingSample = valueAsTrainingSample;
		this.assignedCount = assignedCount;
	}

	@Column(name = "documentID", nullable = false)
	public long getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(long documentId) {
		this.documentId = documentId;
	}

	@Column(name = "crisisID", nullable = false)
	public int getCrisisId() {
		return this.crisisId;
	}

	public void setCrisisId(int crisisId) {
		this.crisisId = crisisId;
	}

	@Column(name = "attributeInfo", length = 358)
	public String getAttributeInfo() {
		return this.attributeInfo;
	}

	public void setAttributeInfo(String attributeInfo) {
		this.attributeInfo = attributeInfo;
	}

	@Column(name = "language", nullable = false, length = 5)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "doctype", nullable = false, length = 20)
	public String getDoctype() {
		return this.doctype;
	}

	public void setDoctype(String doctype) {
		this.doctype = doctype;
	}

	@Column(name = "data", nullable = false, length = 65535)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Column(name = "valueAsTrainingSample", nullable = false, precision = 22, scale = 0)
	public double getValueAsTrainingSample() {
		return this.valueAsTrainingSample;
	}

	public void setValueAsTrainingSample(double valueAsTrainingSample) {
		this.valueAsTrainingSample = valueAsTrainingSample;
	}

	@Column(name = "assignedCount", precision = 23, scale = 0)
	public BigDecimal getAssignedCount() {
		return this.assignedCount;
	}

	public void setAssignedCount(BigDecimal assignedCount) {
		this.assignedCount = assignedCount;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaskBufferId))
			return false;
		TaskBufferId castOther = (TaskBufferId) other;

		return (this.getDocumentId() == castOther.getDocumentId())
				&& (this.getCrisisId() == castOther.getCrisisId())
				&& ((this.getAttributeInfo() == castOther.getAttributeInfo()) || (this
						.getAttributeInfo() != null
						&& castOther.getAttributeInfo() != null && this
						.getAttributeInfo()
						.equals(castOther.getAttributeInfo())))
				&& ((this.getLanguage() == castOther.getLanguage()) || (this
						.getLanguage() != null
						&& castOther.getLanguage() != null && this
						.getLanguage().equals(castOther.getLanguage())))
				&& ((this.getDoctype() == castOther.getDoctype()) || (this
						.getDoctype() != null && castOther.getDoctype() != null && this
						.getDoctype().equals(castOther.getDoctype())))
				&& ((this.getData() == castOther.getData()) || (this.getData() != null
						&& castOther.getData() != null && this.getData()
						.equals(castOther.getData())))
				&& (this.getValueAsTrainingSample() == castOther
						.getValueAsTrainingSample())
				&& ((this.getAssignedCount() == castOther.getAssignedCount()) || (this
						.getAssignedCount() != null
						&& castOther.getAssignedCount() != null && this
						.getAssignedCount()
						.equals(castOther.getAssignedCount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getDocumentId();
		result = 37 * result + this.getCrisisId();
		result = 37
				* result
				+ (getAttributeInfo() == null ? 0 : this.getAttributeInfo()
						.hashCode());
		result = 37 * result
				+ (getLanguage() == null ? 0 : this.getLanguage().hashCode());
		result = 37 * result
				+ (getDoctype() == null ? 0 : this.getDoctype().hashCode());
		result = 37 * result
				+ (getData() == null ? 0 : this.getData().hashCode());
		result = 37 * result + (int) this.getValueAsTrainingSample();
		result = 37
				* result
				+ (getAssignedCount() == null ? 0 : this.getAssignedCount()
						.hashCode());
		return result;
	}

}
