// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0

package qa.qcri.aidr.predictdb.entities.misc;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "aidr_predict", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Users implements java.io.Serializable {

	private Integer userId;
	private String name;
	private String role;
	private Set nominalAttributes = new HashSet(0);
	private Set crisises = new HashSet(0);

	public Users() {
	}

	public Users(String name, String role) {
		this.name = name;
		this.role = role;
	}

	public Users(String name, String role, Set nominalAttributes, Set crisises) {
		this.name = name;
		this.role = role;
		this.nominalAttributes = nominalAttributes;
		this.crisises = crisises;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "userID", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "role", nullable = false, length = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set getNominalAttributes() {
		return this.nominalAttributes;
	}

	public void setNominalAttributes(Set nominalAttributes) {
		this.nominalAttributes = nominalAttributes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set getCrisises() {
		return this.crisises;
	}

	public void setCrisises(Set crisises) {
		this.crisises = crisises;
	}

}
