// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.dbmanager.entities.task;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DocumentNominalLabelId generated by hbm2java
 */
@Embeddable
public class DocumentNominalLabelId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 236089192979257510L;
	private Long documentId;
	private Long nominalLabelId;
	private Long userId;

	public DocumentNominalLabelId() {
	}

	public DocumentNominalLabelId(Long documentId, Long nominalLabelId,
			Long userId) {
		this.documentId = documentId;
		this.nominalLabelId = nominalLabelId;
		this.userId = userId;
	}

	@Column(name = "documentID", nullable = false)
	public Long getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(Long documentId) {
		this.documentId = documentId;
	}

	@Column(name = "nominalLabelID", nullable = false)
	public Long getNominalLabelId() {
		return this.nominalLabelId;
	}

	public void setNominalLabelId(Long nominalLabelId) {
		this.nominalLabelId = nominalLabelId;
	}

	@Column(name = "userID", nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocumentNominalLabelId))
			return false;
		DocumentNominalLabelId castOther = (DocumentNominalLabelId) other;

		return (this.getDocumentId() == castOther.getDocumentId())
				&& (this.getNominalLabelId() == castOther.getNominalLabelId())
				&& (this.getUserId() == castOther.getUserId());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDocumentId().intValue();
		result = 37 * result + this.getNominalLabelId().intValue();
		result = 37 * result + this.getUserId().intValue();
		return result;
	}

}
