package qa.qcri.aidr.trainer.api.util;

import qa.qcri.aidr.common.code.ConfigurationProperty;

/**
 * @author kushal
 * 
 *         Enum containing all the property keys required by the aidr-trainer-api
 *         module.
 * 
 */
public enum TrainerConfigurationProperty implements ConfigurationProperty {

	REMOTE_TASK_MANAGER_REMOTE_JNDI_NAME("REMOTE_TASK_MANAGER_REMOTE_JNDI_NAME"),
	REMOTE_DB_MANAGER_DOCUMENT_NOMINAL_LABEL_RESOURCE_FACADE_JNDI_NAME("REMOTE_DB_MANAGER_DOCUMENT_NOMINAL_LABEL_RESOURCE_FACADE_JNDI_NAME"),
	REMOTE_DB_MANAGER_NOMINAL_LABEL_RESOURCE_FACADE_JNDI_NAME("REMOTE_DB_MANAGER_NOMINAL_LABEL_RESOURCE_FACADE_JNDI_NAME"),
	REMOTE_DB_MANAGER_DOCUMENT_RESOURCE_FACADE_JNDI_NAME("REMOTE_DB_MANAGER_DOCUMENT_RESOURCE_FACADE_JNDI_NAME"),
	REMOTE_DB_MANAGER_CRISIS_RESOURCE_FACADE_JNDI_NAME("REMOTE_DB_MANAGER_CRISIS_RESOURCE_FACADE_JNDI_NAME"),
	REMOTE_DB_MANAGER_TASK_ASSIGNMENT_RESOURCE_FACADE_JNDI_NAME("REMOTE_DB_MANAGER_TASK_ASSIGNMENT_RESOURCE_FACADE_JNDI_NAME"),
	REMOTE_DB_MANAGER_COLLECTION_RESOURCE_FACADE_JNDI_NAME("REMOTE_DB_MANAGER_COLLECTION_RESOURCE_FACADE_JNDI_NAME"),
	REMOTE_DB_MANAGER_MODEL_FAMILY_RESOURCE_FACADE_JNDI_NAME("REMOTE_DB_MANAGER_MODEL_FAMILY_RESOURCE_FACADE_JNDI_NAME"),
	REMOTE_DB_MANAGER_CUSTOM_UI_TEMPLATE_RESOURCE_FACADE_JNDI_NAME("REMOTE_DB_MANAGER_CUSTOM_UI_TEMPLATE_RESOURCE_FACADE_JNDI_NAME"),
	REMOTE_DB_MANAGER_USERS_RESOURCE_FACADE_JNDI_NAME("REMOTE_DB_MANAGER_USERS_RESOURCE_FACADE_JNDI_NAME"),
	REDIS_HOST("REDIS_HOST"),
	REDIS_PORT("REDIS_PORT");
	
	private final String configurationProperty;

	private TrainerConfigurationProperty(String property) {
		configurationProperty = property;
	}

	@Override
	public String getName() {
		return this.configurationProperty;
	}

}
