package qa.qcri.aidr.utils;

import qa.qcri.aidr.common.code.ConfigurationProperty;

public enum PersisterConfigurationProperty implements ConfigurationProperty {

	DEFAULT_PERSISTER_FILE_PATH("DEFAULT_PERSISTER_FILE_PATH"), SCD1_URL(
			"SCD1_URL"), FETCHER_CHANNEL("FETCHER_CHANNEL"), TAGGER_CHANNEL(
			"TAGGER_CHANNEL"), COLLECTION_CHANNEL("COLLECTION_CHANNEL"), DEFAULT_PERSISTER(
			"DEFAULT_PERSISTER"), DEFAULT_PERSISTER_CODE(
			"DEFAULT_PERSISTER_CODE"), DEFAULT_FILE_VOLUMN_LIMIT(
			"DEFAULT_FILE_VOLUMN_LIMIT"), TWEETS_EXPORT_LIMIT_100K(
			"TWEETS_EXPORT_LIMIT_100K"), DEFAULT_FILE_WRITER_BUFFER_SIZE(
			"DEFAULT_FILE_WRITER_BUFFER_SIZE"), DEFAULT_TWEETID_VOLUME_LIMIT(
			"DEFAULT_TWEETID_VOLUME_LIMIT"), LOG_FILE_NAME("LOG_FILE_NAME"), TWEET_DOWNLOAD_LIMIT_MSG_PREFIX(
			"TWEET_DOWNLOAD_LIMIT_MSG_PREFIX"), TWEET_DOWNLOAD_LIMIT_MSG_SUFFIX(
			"TWEET_DOWNLOAD_LIMIT_MSG_SUFFIX"), PERSISTER_CHANGE_NOTIFY_MSG(
			"PERSISTER_CHANGE_NOTIFY_MSG"), MANAGER_URL("managerUrl"), PERSISTER_LOAD_LIMIT(
			"PERSISTER_LOAD_LIMIT"), PERSISTER_LOAD_CHECK_INTERVAL_MINUTES(
			"PERSISTER_LOAD_CHECK_INTERVAL_MINUTES"), INPUT_PORT("INPUT_PORT"), OUTPUT_PORT(
			"OUTPUT_PORT"), REDIS_HOST("REDIS_HOST"), REDIS_PORT("REDIS_PORT"), STATUS_CODE_ERROR(
			"STATUS_CODE_ERROR"), TAGGER_MAIN_URL("taggerMainUrl");

	private final String configurationProperty;

	private PersisterConfigurationProperty(String property) {
		configurationProperty = property;
	}

	@Override
	public String getName() {
		return this.configurationProperty;
	}

}
