// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.dbmanager.entities.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelNominalLabelId generated by hbm2java
 */
@Embeddable
public class ModelNominalLabelId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4746086718641115270L;
	
	@Column(name = "modelID", nullable = false)
	private Long modelId;

	@Column(name = "nominalLabelID", nullable = false)
	private Long nominalLabelId;

	public ModelNominalLabelId() {
	}

	public ModelNominalLabelId(Long modelId, Long nominalLabelId) {
		this.modelId = modelId;
		this.nominalLabelId = nominalLabelId;
	}


	public Long getModelId() {
		return this.modelId;
	}

	public void setModelId(Long modelId) {
		this.modelId = modelId;
	}


	public Long getNominalLabelId() {
		return this.nominalLabelId;
	}

	public void setNominalLabelId(Long nominalLabelId) {
		this.nominalLabelId = nominalLabelId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelNominalLabelId))
			return false;
		ModelNominalLabelId castOther = (ModelNominalLabelId) other;

		return (this.getModelId() == castOther.getModelId())
				&& (this.getNominalLabelId() == castOther.getNominalLabelId());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getModelId().intValue();
		result = 37 * result + this.getNominalLabelId().intValue();
		return result;
	}

}
