// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.dbmanager.entities.model;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.Hibernate;
import org.hibernate.collection.internal.PersistentList;

import qa.qcri.aidr.dbmanager.entities.misc.Crisis;

/**
 * ModelFamily generated by hbm2java
 */
@Entity
@Table(name = "model_family", catalog = "aidr_predict", uniqueConstraints = @UniqueConstraint(columnNames = {
    "crisisID", "nominalAttributeID"}))
public class ModelFamily implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -1064917491408243168L;
	private Long modelFamilyId;
	private NominalAttribute nominalAttribute;
	private Crisis crisis;
	private boolean isActive;
	private List<Model> models = null;

	public ModelFamily() {
	}

	public ModelFamily(NominalAttribute nominalAttribute, Crisis crisis,
			boolean isActive) {
		this.nominalAttribute = nominalAttribute;
		this.crisis = crisis;
		this.isActive = isActive;
	}

	public ModelFamily(NominalAttribute nominalAttribute, Crisis crisis,
			boolean isActive, List<Model> models) {
		this.crisis = crisis;
		this.isActive = isActive;
		this.models = models;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "modelFamilyID", unique = true, nullable = false)
	public Long getModelFamilyId() {
		return this.modelFamilyId;
	}

	public void setModelFamilyId(Long modelFamilyId) {
		this.modelFamilyId = modelFamilyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nominalAttributeID", nullable = false)
	public NominalAttribute getNominalAttribute() {
		return this.nominalAttribute;
	}

	public void setNominalAttribute(NominalAttribute nominalAttribute) {
		this.nominalAttribute = nominalAttribute;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "crisisID", nullable = false)
	public Crisis getCrisis() {
		return this.crisis;
	}

	public void setCrisis(Crisis crisis) {
		this.crisis = crisis;
	}

	@Column(name = "isActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelFamily")
	public List<Model> getModels() {
		return this.models;
	}

	public void setModels(List<Model> models) {
		this.models = models;
	}
	
	public boolean hasModels() {
		return Hibernate.isInitialized(this.models);
	}
	
	public boolean hasCrisis() {
		return Hibernate.isInitialized(this.crisis);
	}

}
