// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.dbmanager.entities.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NominalAttributeDependentLabel generated by hbm2java
 */
@Entity
@Table(name = "nominal_attribute_dependent_label", catalog = "aidr_predict")
public class NominalAttributeDependentLabel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4200478432355906054L;
	private NominalAttributeDependentLabelId id;
	private NominalLabel nominalLabel;
	private NominalAttribute nominalAttribute;
	private Float threshold;

	public NominalAttributeDependentLabel() {
	}

	public NominalAttributeDependentLabel(NominalAttributeDependentLabelId id,
			NominalLabel nominalLabel, NominalAttribute nominalAttribute) {
		this.id = id;
		this.nominalLabel = nominalLabel;
		this.nominalAttribute = nominalAttribute;
	}

	public NominalAttributeDependentLabel(NominalAttributeDependentLabelId id,
			NominalLabel nominalLabel, NominalAttribute nominalAttribute,
			Float threshold) {
		this.id = id;
		this.nominalLabel = nominalLabel;
		this.nominalAttribute = nominalAttribute;
		this.threshold = threshold;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nominalAttributeId", column = @Column(name = "nominalAttributeID", nullable = false)),
			@AttributeOverride(name = "nominalLabelId", column = @Column(name = "nominalLabelID", nullable = false)) })
	public NominalAttributeDependentLabelId getId() {
		return this.id;
	}

	public void setId(NominalAttributeDependentLabelId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nominalLabelID", nullable = false, insertable = false, updatable = false)
	public NominalLabel getNominalLabel() {
		return this.nominalLabel;
	}

	public void setNominalLabel(NominalLabel nominalLabel) {
		this.nominalLabel = nominalLabel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nominalAttributeID", nullable = false, insertable = false, updatable = false)
	public NominalAttribute getNominalAttribute() {
		return this.nominalAttribute;
	}

	public void setNominalAttribute(NominalAttribute nominalAttribute) {
		this.nominalAttribute = nominalAttribute;
	}

	@Column(name = "threshold", precision = 12, scale = 0)
	public Float getThreshold() {
		return this.threshold;
	}

	public void setThreshold(Float threshold) {
		this.threshold = threshold;
	}

}
