// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
package qa.qcri.aidr.dbmanager.entities.model;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.Hibernate;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import qa.qcri.aidr.dbmanager.entities.task.DocumentNominalLabel;

/**
 * NominalLabel generated by hbm2java
 */
@Entity
@Table(name = "nominal_label", catalog = "aidr_predict")
public class NominalLabel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8467620180557868662L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "nominalLabelID", unique = true, nullable = false)
	private Long nominalLabelId;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "nominalAttributeID", nullable = false)
	@JsonBackReference
	private NominalAttribute nominalAttribute;
	
	@Column(name = "nominalLabelCode", nullable = false, length = 64)
	private String nominalLabelCode;
	
	@Column(name = "name", nullable = false, length = 140)
	private String name;
	
	@Column(name = "description", nullable = false, length = 600)
	private String description;
	
	@Column(name = "sequence", nullable = false)
	private Integer sequence;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nominalLabel")
	@JsonManagedReference
	private List<ModelNominalLabel> modelNominalLabels = null;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nominalLabel")
	@JsonManagedReference
	private List<DocumentNominalLabel> documentNominalLabels = null;

	public NominalLabel() {
	}

	public NominalLabel(NominalAttribute nominalAttribute,
			String nominalLabelCode, String name, String description,
			Integer sequence) {
		this.nominalAttribute = nominalAttribute;
		this.nominalLabelCode = nominalLabelCode;
		this.name = name;
		this.description = description;
		this.sequence = sequence;
	}

	public NominalLabel(NominalAttribute nominalAttribute,
			String nominalLabelCode, String name, String description,
			Integer sequence, List<ModelNominalLabel> modelNominalLabels,
			List<DocumentNominalLabel> documentNominalLabels) {
		this.nominalAttribute = nominalAttribute;
		this.nominalLabelCode = nominalLabelCode;
		this.name = name;
		this.description = description;
		this.sequence = sequence;
		this.modelNominalLabels = modelNominalLabels;
		this.documentNominalLabels = documentNominalLabels;
	}


	public Long getNominalLabelId() {
		return this.nominalLabelId;
	}

	public void setNominalLabelId(Long nominalLabelId) {
		this.nominalLabelId = nominalLabelId;
	}


	public NominalAttribute getNominalAttribute() {
		return this.nominalAttribute;
	}

	public void setNominalAttribute(NominalAttribute nominalAttribute) {
		this.nominalAttribute = nominalAttribute;
	}


	public String getNominalLabelCode() {
		return this.nominalLabelCode;
	}

	public void setNominalLabelCode(String nominalLabelCode) {
		this.nominalLabelCode = nominalLabelCode;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	
	public List<ModelNominalLabel> getModelNominalLabels() {
		return this.modelNominalLabels;
	}

	public void setModelNominalLabels(List<ModelNominalLabel> modelNominalLabels) {
		this.modelNominalLabels = modelNominalLabels;
	}

	public List<DocumentNominalLabel> getDocumentNominalLabels() {
		return this.documentNominalLabels;
	}

	public void setDocumentNominalLabels(List<DocumentNominalLabel> documentNominalLabels) {
		this.documentNominalLabels = documentNominalLabels;
	}

	public boolean hasDocumentNominalLabels() {
		return Hibernate.isInitialized(this.documentNominalLabels);
	}
	
	public boolean hasModelNominalLabels() {
		return Hibernate.isInitialized(this.modelNominalLabels);
	}
	
	public boolean hasNominalAttribute() {
		return Hibernate.isInitialized(this.nominalAttribute);
	}
}
