CREATE TABLE `AIDR_COLLECTION_LOG` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `collectionId` INT(11) NOT NULL,
  `track` longtext NOT NULL,
  `follow` VARCHAR(255) DEFAULT NULL,
  `geo` VARCHAR(255) DEFAULT NULL,
  `langFilters` VARCHAR(255) DEFAULT NULL,  
  `startDate` DATETIME DEFAULT NULL,
  `endDate` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8$$



DELIMITER $$
CREATE
    TRIGGER LOG_COLLECTION_TRIGGER AFTER UPDATE
    ON AIDR_COLLECTION
    FOR EACH ROW 
	BEGIN
           IF(NEW.STATUS != OLD.STATUS)
           THEN
           IF(NEW.STATUS='RUNNING')
            THEN
             INSERT INTO AIDR_COLLECTION_LOG (COLLECTIONID,TRACK,FOLLOW,GEO,LANGFILTERS, STARTDATE,ENDDATE) 
                VALUES (NEW.ID,NEW.TRACK,NEW.FOLLOW,NEW.GEO, NEW.LANGFILTERS, NEW.STARTDATE,NEW.ENDDATE);
             ELSEIF (NEW.STATUS='STOPPED')
             THEN
                UPDATE AIDR_COLLECTION_LOG SET ENDDATE = NEW.ENDDATE WHERE COLLECTIONID =NEW.ID;
    
            END IF;
           END IF;           
    END$$