
DELETE FROM `crisis_type`; 
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (10, '(Not defined)');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1100, 'Natural Hazard: Geophysical: Earthquake and/or Tsunami');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1110, 'Natural Hazard: Geophysical: Volcano');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1120, 'Natural Hazard: Geophysical: Dry mass movement (rockfall, avalanche, landslide, subsidence)');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1130, 'Natural Hazard: Meteorological: Storm (tropical, cyclone, tornado, blizzard, dust storm)');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1140, 'Natural Hazard: Hydrological: Flood (river-, flash-, coastal-)');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1150, 'Natural Hazard: Hydrological: Wet mass movement (rockfall, avalanche, landslide, subsidence)');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1160, 'Natural Hazard: Climatological: Extreme temperature (heat/cold wave)');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1170, 'Natural Hazard: Climatological: Drought');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1180, 'Natural Hazard: Climatological: Fire (forest, bush, grass, wild)');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1190, 'Natural Hazard: Biological: Epidemic (diseases, insects, animals)');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1200, 'Natural Hazard: Other');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1210, 'Human Induced: War or armed conflict, incl. acts of war');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1220, 'Human Induced: Terrorist attack against civilians');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1230, 'Human Induced: Demonstrations (peaceful or violent, riots)');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1240, 'Human Induced: Pollution (hazardous material, oil spill, etc.)');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1250, 'Human Induced: Radiation, including nuclear explosion');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1260, 'Human Induced: Transportation accident (train, boat, plane, etc.)');
INSERT INTO `crisis_type` (`crisisTypeID`, `name`) values (1270, 'Human Induced: Other');