// default package
// Generated Nov 24, 2014 4:55:08 PM by Hibernate Tools 4.0.0
/**
 * Implements the entity corresponding to the users table in the aidr_predict DB
 * 
 * @author Koushik
 */
package qa.qcri.aidr.dbmanager.entities.misc;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/*
 * Users generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "aidr_predict")
public class Users implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -103376812342618433L;

	@Column(name="user_name", unique=true, nullable=false)
	private String userName;
	private String provider;
	private String locale;
	
	@Column(name="api_key", nullable=false, unique=true)
	private String apiKey;
	@Id @GeneratedValue(strategy=GenerationType.AUTO) 
	protected Long id;
	
	@Column(updatable = false, nullable=false, name = "created_at")
	private Timestamp createdAt;
	
	@Column(nullable=false, name = "updated_at")
	private Timestamp updatedAt;
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Timestamp getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public String getApiKey() {
		return apiKey;
	}

	public void setApiKey(String apiKey) {
		this.apiKey = apiKey;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getProvider() {
		return provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	public String getLocale() {
		return locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}
}
